{
  "artifacts": [], 
  "command": "main", 
  "experiment": {
    "base_dir": "/home/v-chaoqw/MYSFC-ORI", 
    "dependencies": [
      "numpy==1.12.1", 
      "sacred==0.7.2"
    ], 
    "mainfile": "configuration.py", 
    "name": "Siam-FC", 
    "repositories": [], 
    "sources": [
      [
        "configuration.py", 
        "_sources/configuration_71abb6f46631430d407c749e3f249e55.py"
      ]
    ]
  }, 
  "fail_trace": [
    "Traceback (most recent call last):\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/sacred/config/captured_function.py\", line 48, in captured_function\n    result = wrapped(*args, **kwargs)\n", 
    "  File \"train_track_model.py\", line 577, in main\n    max_to_keep=train_config['max_checkpoints_to_keep'])\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/saver.py\", line 1056, in __init__\n    self.build()\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/saver.py\", line 1086, in build\n    restore_sequentially=self._restore_sequentially)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/training/saver.py\", line 680, in build\n    filename_tensor = constant_op.constant(filename)\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in constant\n    attrs={\"value\": tensor_value, \"dtype\": dtype_value}, name=name).outputs[0]\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 2288, in create_op\n    self._check_not_finalized()\n", 
    "  File \"/home/v-chaoqw/anaconda2/envs/hdrnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 2011, in _check_not_finalized\n    raise RuntimeError(\"Graph is finalized and cannot be modified.\")\n", 
    "RuntimeError: Graph is finalized and cannot be modified.\n"
  ], 
  "heartbeat": "2017-12-17T02:44:08.841105", 
  "host": {
    "ENV": {}, 
    "cpu": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz", 
    "gpus": {
      "driver_version": "384.81", 
      "gpus": [
        {
          "model": "Tesla K80", 
          "persistence_mode": false, 
          "total_memory": 11439
        }, 
        {
          "model": "Tesla K80", 
          "persistence_mode": false, 
          "total_memory": 11439
        }
      ]
    }, 
    "hostname": "GCRAZGDL116", 
    "os": [
      "Linux", 
      "Linux-4.4.0-101-generic-x86_64-with-debian-stretch-sid"
    ], 
    "python_version": "2.7.14"
  }, 
  "meta": {
    "command": "main", 
    "options": {
      "--beat_interval": null, 
      "--capture": null, 
      "--comment": null, 
      "--debug": false, 
      "--enforce_clean": false, 
      "--file_storage": null, 
      "--force": false, 
      "--help": false, 
      "--loglevel": null, 
      "--mongo_db": null, 
      "--name": null, 
      "--pdb": false, 
      "--print_config": false, 
      "--priority": null, 
      "--queue": false, 
      "--sql": null, 
      "--tiny_db": null, 
      "--unobserved": false, 
      "COMMAND": null, 
      "UPDATE": [
        "sfc", 
        "workstation"
      ], 
      "help": false, 
      "with": true
    }
  }, 
  "resources": [], 
  "result": null, 
  "start_time": "2017-12-17T02:43:57.011489", 
  "status": "FAILED", 
  "stop_time": "2017-12-17T02:44:08.843435"
}